# This is a TOML document
amount = "12,25"
content = "TOML Content Example"
count = "25"
date = "2022-08-10T14:14:48+00:00"
title = "TOML Title Example"

# Child Object
[database]
server = "localhost"

# Child Object
[ftp]
server = "ip"
